#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLS.EmailSubscriptions.HangfireExtension
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\ViewPage1.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\ViewPage1.cshtml"
    using BLS.EmailSubscriptions.HangfireExtension.Data;
    
    #line default
    #line hidden
    
    #line 4 "..\..\ViewPage1.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ViewPage1 : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





WriteLiteral("\r\n<div class=\"col-12\">\r\n\r\n</div>");


        }
    }
}
#pragma warning restore 1591
